security:
  basic:
    enabled: false
  user:
    name: oauth
    password: web-local
    role: ADMIN
    
logging:  
#  file: logs/${spring.application.name}.log
  level:
    org.springframework.security.authentication: 'INFO'
    org.springframework.security.web: 'INFO'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
